INSERT INTO CITAS (NOMBRE_PACIENTE, EMAIL_PACIENTE, ESPECIALIDAD, NOMBRE_MEDICO, FECHA_CITA, HORA_CITA, ESTADO)
VALUES ('Matias Munoz', 'matias@correo.cl', 'Medicina General', 'Dra. Andrea Soto', DATE '2026-05-10', '10:30', 'PROGRAMADA');

INSERT INTO CITAS (NOMBRE_PACIENTE, EMAIL_PACIENTE, ESPECIALIDAD, NOMBRE_MEDICO, FECHA_CITA, HORA_CITA, ESTADO)
VALUES ('Valentina Reyes', 'valentina@correo.cl', 'Dermatologia', 'Dr. Carlos Reyes', DATE '2026-05-10', '11:00', 'CONFIRMADA');

INSERT INTO CITAS (NOMBRE_PACIENTE, EMAIL_PACIENTE, ESPECIALIDAD, NOMBRE_MEDICO, FECHA_CITA, HORA_CITA, ESTADO)
VALUES ('Carlos Diaz', 'carlos@correo.cl', 'Odontologia', 'Dra. Camila Perez', DATE '2026-05-11', '09:00', 'CANCELADA');
