INSERT INTO PEDIDOS (NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, NOMBRE_CLIENTE, FECHA_PEDIDO, ESTADO)
VALUES ('Alimento Premium Perro 15kg', 'Alimento', 2, 35990.00, 'Matias Munoz', DATE '2026-05-01', 'PENDIENTE');

INSERT INTO PEDIDOS (NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, NOMBRE_CLIENTE, FECHA_PEDIDO, ESTADO)
VALUES ('Arena Sanitaria Gato 10kg', 'Higiene', 3, 8990.00, 'Valentina Reyes', DATE '2026-05-02', 'CONFIRMADO');

INSERT INTO PEDIDOS (NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, NOMBRE_CLIENTE, FECHA_PEDIDO, ESTADO)
VALUES ('Collar Antipulgas Perro', 'Salud', 1, 12990.00, 'Carlos Diaz', DATE '2026-05-03', 'ENVIADO');
